version: "3.7"

services:
  app:
    build:
      context: ..
    env_file:
      - ../config.py
    container_name: app
    command:
      - python manage.py runserver 0.0.0.0:8000
    ports:
      - 9999:8000
    depends_on:
      - db

  db:
    image: postgres:13.3
    ports:
      - '5432:5432'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always

